# Generated by Django 2.1.5 on 2019-09-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0002_auto_20190921_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
